"""Administrative clauses must not create scope or erase a separately purchased app."""
import pytest

from anthrion_signal.discovery import prefilter


@pytest.mark.parametrize("title,description", [
    ("Concrete work", "Questions generated by artificial intelligence will not be answered."),
    ("Component supply", "Pricing for this quotation is valid for 60 days. Contractual documents are sent by electronic commerce methods such as email. Technical data packages include software."),
    ("Inspection services", "IPP is a secure web-based electronic invoicing system provided by the Treasury. Contractor Performance Assessment Reporting System records will be consulted."),
    ("Supply of fuel", "To gain access to ordering, offerors must request applicable user roles via the Account Management and Provisioning System website."),
    ("Serial subscriptions", "Obtain printed journals, publisher pricing, accurate billing and subscription management services."),
    ("OEM tow line", "To ensure safety and integration with existing systems, only authorized vendors may supply the synthetic fiber tow line."),
    ("Receiver repair", "Equipment; Example Systems Information & Electronic Systems Integration; Company Name; repair of supplied parts."),
    ("AI system", "This procurement consists of an artificial intelligence computing system and associated software/licensing, installation and maintenance."),
])
def test_administrative_and_physical_scope_is_not_software_work(signal, config, title, description):
    signal.title, signal.description, signal.cpv_codes = title, description, []
    signal.source = "sam"
    prefilter([signal], config["company_profile"], config["search_terms"], config["capabilities"])
    assert signal.prefilter_score < config["capabilities"]["discovery"]["minimum_candidate_score"]
    original = signal.description
    signal.description += " Separately implement a Salesforce CRM platform with API integration and customer casework."
    prefilter([signal], config["company_profile"], config["search_terms"], config["capabilities"])
    assert signal.prefilter_score >= config["capabilities"]["discovery"]["minimum_candidate_score"]
    assert "salesforce" in signal.matched_capabilities and not signal.exclusion_reasons
    assert signal.description.startswith(original)


@pytest.mark.parametrize("description", [
    "Build a replacement invoice processing platform and integrate its invoicing system with the finance application.",
    "Develop subscription management software for journal publishers with automated billing.",
    "Develop an artificial intelligence application alongside the new GPU computing resources.",
    "Implement an Enterprise Asset Management software platform for the barracks maintenance team.",
    "Formal final acceptance after complete system integration.",
    "Förmliche Gesamtabnahme nach vollständiger Systemintegration.",
])
def test_real_software_in_administrative_or_physical_sectors_stays_visible(signal, config, description):
    signal.title, signal.description, signal.cpv_codes = "Commissioned technology services", description, []
    prefilter([signal], config["company_profile"], config["search_terms"], config["capabilities"])
    assert signal.prefilter_score >= config["capabilities"]["discovery"]["minimum_candidate_score"]
    assert not signal.exclusion_reasons
