"""Administrative clauses must not create scope or erase a separately purchased app."""
import pytest

from anthrion_signal.discovery import prefilter


@pytest.mark.parametrize("title,description", [
    ("Uncrewed Air System", "Supply prototype equipment including an on board computer. Emerging technologies include artificial intelligence and machine learning."),
    ("Inmate Purchasing Plan", "Supply retail clothing and personal effects using an existing ordering system. The supplier must have a reporting system capable of generating various reports."),
    ("Enclosed trailers", "Procure enclosed trailers. You will need an SAP Ariba business account to view tender opportunities and submit bids electronically on SAP Ariba Discovery. Once your account is created, please note to check your email and click the Activation link sent from the ARIBA Commerce Cloud to complete your registration."),
    ("Sally Port Gates Drive Actuator Replacement", "Replace the actuators, magnetic locks, conduits and gate operating controls. Associated work includes system integration, commissioning and training for a complete gate system."),
    ("Alarm System Monitoring Service", "Provide remote alarm system management services, 24/7 call center, technical verifications and equipment parts including regional travel."),
    ("Concrete work", "Questions generated by artificial intelligence will not be answered."),
    ("Component supply", "Pricing for this quotation is valid for 60 days. Contractual documents are sent by electronic commerce methods such as email. Technical data packages include software."),
    ("Inspection services", "IPP is a secure web-based electronic invoicing system provided by the Treasury. Contractor Performance Assessment Reporting System records will be consulted."),
    ("Supply of fuel", "To gain access to ordering, offerors must request applicable user roles via the Account Management and Provisioning System website."),
    ("Serial subscriptions", "Obtain printed journals, publisher pricing, accurate billing and subscription management services."),
    ("OEM tow line", "To ensure safety and integration with existing systems, only authorized vendors may supply the synthetic fiber tow line."),
    ("Receiver repair", "Equipment; Example Systems Information & Electronic Systems Integration; Company Name; repair of supplied parts."),
    ("Receiver repair", "Equipment;Example Systems Information &Electronic Systems Integration; Company Name; repair of supplied parts."),
    ("AI system", "This procurement consists of an artificial intelligence computing system and associated software/licensing, installation and maintenance."),
    ("Appliance replacement", "Supply breakroom appliances. Clauses: 52.204-16 Commercial and Government Entity Code Reporting (Aug 2020) 52.204-23 Prohibition on Contracting for Hardware, Software, and Services Developed or Provided by Kaspersky Lab (Dec 2023)."),
    ("Video component", "CONTACT INFORMATION|4|N100.6|CRM|555-123-4567|contact@example.org| Supply a video converter."),
    ("Site equipment", "Use the AI Phone (video/audio system) at the door to announce themselves to the security guard for entry."),
    ("Building services", "Provide snow removal for the 127?? Software Engineering Group (127 SWEG). Clear walkways for each 127 Software Engineering Group building."),
    ("Grounds services", "The contractor shall provide an after-hours contact number in the Emergency Mass Notification System for personnel. Foreign nationals may remove themselves from the Emergency Mass Notification System at any time."),
])
def test_administrative_and_physical_scope_is_not_software_work(signal, config, title, description):
    signal.title, signal.description, signal.cpv_codes = title, description, []
    signal.source = "sam"
    prefilter([signal], config["company_profile"], config["search_terms"], config["capabilities"])
    assert signal.prefilter_score < config["capabilities"]["discovery"]["minimum_candidate_score"]
    original = signal.description
    signal.description += " Separately implement a Salesforce CRM platform with API integration and customer casework."
    prefilter([signal], config["company_profile"], config["search_terms"], config["capabilities"])
    assert signal.prefilter_score >= config["capabilities"]["discovery"]["minimum_candidate_score"]
    assert "salesforce" in signal.matched_capabilities and not signal.exclusion_reasons
    assert signal.description.startswith(original)


@pytest.mark.parametrize("description", [
    "52.204-16 Commercial and Government Entity Code Reporting (Aug 2020) Implement a CRM reporting platform.",
    "Provide a dedicated software engineering group to build business applications.",
    "The supplier must have a reporting system and must implement a separate reporting system for the contracting authority.",
    "For the Information Technology Department, implement an AI assistant for residents.",
    "Provide CRM support. CONTACT INFORMATION|4|N100.6|CRM|555-123-4567|contact@example.org|",
    "Develop an emergency notification system that stores after-hours contact information for personnel.",
    "Implement an AI visitor-management platform; visitors use the AI Phone at the door for entry.",
])
def test_real_delivery_survives_recipient_contact_and_regulatory_context(signal, config, description):
    signal.title, signal.description, signal.cpv_codes = "Service requirement", description, []
    signal.source = "sam"
    prefilter([signal], config["company_profile"], config["search_terms"], config["capabilities"])
    assert signal.prefilter_score >= config["capabilities"]["discovery"]["minimum_candidate_score"]
    assert not signal.exclusion_reasons
    assert signal.description == description
    assert all(item["quote"] in getattr(signal, item["field"]) for item in signal.capability_evidence)


@pytest.mark.parametrize("description", [
    "Build a replacement invoice processing platform and integrate its invoicing system with the finance application.",
    "Develop subscription management software for journal publishers with automated billing.",
    "Develop an artificial intelligence application alongside the new GPU computing resources.",
    "Implement an Enterprise Asset Management software platform for the barracks maintenance team.",
    "Formal final acceptance after complete system integration.",
    "Förmliche Gesamtabnahme nach vollständiger Systemintegration.",
])
def test_real_software_in_administrative_or_physical_sectors_stays_visible(signal, config, description):
    signal.title, signal.description, signal.cpv_codes = "Commissioned technology services", description, []
    prefilter([signal], config["company_profile"], config["search_terms"], config["capabilities"])
    assert signal.prefilter_score >= config["capabilities"]["discovery"]["minimum_candidate_score"]
    assert not signal.exclusion_reasons
